import { Geist, Geist_Mono, Exo_2 } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/navbar";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo2 = Exo_2({
  variable: "--font-exo-2",
  subsets: ["latin"],
  weight: ["400", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${exo2.variable} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col pt-24 md:pt-20 text-white"
        style={{ backgroundColor: "#1d1e25" }}
      >
        <Navbar />
        {children}
        <footer className="w-full bg-[#1d1e25] py-4 text-center">
          <a className="hmm" href="https://github.com/re1exe" target="_blank">
            <p className="credit">Some code by @Re1</p>
          </a>
        </footer>
      <Analytics/>
      </body>
    </html>
  );
}
